backend:
  name: git-gateway
  branch: cms # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "Principal"
    editor:
       preview: false
    files:
      - file: content/home.md
        label: "Página principal, acerca de y contacto"
        name: "home"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Texto del banner", name: "heroTitle", widget: "string"}
          - {label: "Tarjetas de la página principal", name: "indexCards", widget: "list", allow_add: false, fields: [
              {label: "Título", name: "title", widget: "string"},
              {label: "Enlace", name: "link", widget: "string"},
              {label: "Imagen", name: "image", widget: "string"},
              {label: "Texto", name: "text", widget: "string"}]}
          - {label: "Contacto", name: "contact", widget: "object", fields: [
              {label: "Dirección", name: "address", widget: "string"},
              {label: "Teléfonos", name: "phone", widget: "string"},
              {label: "email", name: "email", widget: "string"},
              {label: "Sitio web", name: "web", widget: "string"}]}
          - {label: "Acerca de", name: "body", widget: "markdown"}
  - name: "references"
    label: "Bibliografías"
    editor:
       preview: false
    folder: "content/references"
    create: false
    slug: "{{id}}"
    fields:
      - {label: "Id", name: "id", widget: "hidden", required: true}
      - {label: "Ancestro", name: "parent", widget: "hidden", required: false}
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: "Lista de referencias", name: "references", widget: "list", fields: [
          {label: "Abreviación", name: "referencekey", widget: "string", required: true},
          {label: "Referencia", name: "reference", widget: "text", required: true}]}
  - name: "cases"
    label: "Estudios de caso"
    editor:
       preview: false
    folder: "content/cases"
    path: "{{slug}}/content"
    create: false
    slug: "{{case}}"
    media_folder: ''
    fields:
      - {label: "Caso", name: "case", widget: "hidden", required: true}
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: "Autores", name: "title", widget: "string", required: true}
      - {label: "Imagen de portada", name: "cardimage", widget: "image", allow_multiple: false, required: true}
      - {label: "Unidades de paisaje", name: "landscapeunits", widget: "string", required: true}
      - {label: "Localidad", name: "locality", widget: "string", required: true}
      - {label: "Estados", name: "states", widget: "string", required: true}
      - {label: "Área", name: "area", widget: "string", required: true}
      - {label: "Área (en formato texto opcional)", name: "areatext", widget: "string", required: false}
      - {label: "Columnas de la tabla de ficha", name: "cardtablecolumns", widget: "list", required: true}
      - {label: "Filas de la tabla de ficha", name: "cardtablerows", widget: "list", required: true}
      - {label: "¿Íconos alineados a la izquierda?", name: "leftJustifyIcons", widget: "boolean", required: false}
      - {label: "Habilitar desplazamiento de la tabla?", name: "enableTableScroll", widget: "boolean", required: false}
      - {label: "Imagenes", name: "photos", widget: "list", fields: [
          {label: "Etiqueta", name: "photokey", widget: "string", required: true},
          {label: "Url", name: "photourl", widget: "image", allow_multiple: false, required: true},
          {label: "Subtítulo", name: "photocaption", widget: "string", required: true}]}
      - {label: "Texto", name: "body", widget: "markdown"}
  - name: "units"
    label: "Unidades de paisaje"
    editor:
       preview: false
    folder: "content/units"
    path: "{{slug}}/content"
    create: false
    slug: "{{region}}"
    media_folder: ''
    fields:
      - {label: "Región", name: "region", widget: "hidden", required: true}
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: "Imagen de portada", name: "cardimage", widget: "image", allow_multiple: false, required: true}
      - {label: "Subtítulo de la imagen de portada", name: "cardimagecaption", widget: "string", required: true}
      - {label: "Imagenes", name: "photos", widget: "list", fields: [
          {label: "Etiqueta", name: "photokey", widget: "string", required: true},
          {label: "Url", name: "photourl", widget: "image", allow_multiple: false, required: true},
          {label: "Subtítulo", name: "photocaption", widget: "string", required: true}]}
      - {label: "Texto", name: "body", widget: "text"}
