backend:
  name: git-gateway
  branch: cms # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
media_folder_relative: true

collections:
  - name: "home"
    label: "Principal"
    editor:
       preview: false
    files:
      - file: content/home.md
        label: "Página principal, acerca de y contacto"
        name: "home"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Texto del banner", name: "heroTitle", widget: "string"}
          - {label: "Tarjetas de la página principal", name: "indexCards", widget: "list", fields: [
              {label: "Título", name: "title", widget: "string"},
              {label: "Enlace", name: "link", widget: "string"},
              {label: "Imagen", name: "image", widget: "string"},
              {label: "Texto", name: "text", widget: "string"}]}
          - {label: "Contacto", name: "contact", widget: "object", fields: [
              {label: "Dirección", name: "address", widget: "string"},
              {label: "Teléfonos", name: "phone", widget: "string"},
              {label: "email", name: "email", widget: "string"},
              {label: "Sitio web", name: "web", widget: "string"}]}
          - {label: "Acerca de", name: "body", widget: "markdown"}
  - name: "units" #
    label: "Unidades de paisaje"
    editor:
       preview: false
    identifier_field: region
    folder: "content/units"
    path: "{{slug}}/content.md"
    create: false
    slug: "{{region}}"
    media_folder: ''
    fields:
      - {label: "Región", name: "region", widget: "string", required: true}
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: "Imagen de portada", name: "cardimage", widget: "string", required: true}
      - {label: "Subtítulo de la imagen de portada", name: "cardimagecaption", widget: "string", required: true}
      - {label: "Imagenes", name: "photos", widget: "list", fields: [
          {label: "Etiqueta", name: "photokey", widget: "string", required: true},
          {label: "Url", name: "photourl", widget: "string", required: true},
          {label: "Subtítulo", name: "photocaption", widget: "string", required: true}]}
      - {label: "Texto", name: "body", widget: "markdown"}
